// Build an exact first-party fallback snapshot. It carries the same content version.
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'data/packs/bentonville.json'),'utf8');
const pack=require('../game-core.js').validatePack(JSON.parse(source));
require('./content-io.cjs').writeAtomic(path.join(root,'builtin-pack.js'),`// Generated by npm run build:content. Edit the authoring source, not this file.\nconst CarmenBuiltinPack = ${JSON.stringify(pack)};\n`);
